### ISSUE TITLE
Partitions disappear on some special view angles

### ISSUE THREAD

**Issue by yzslab** [DekuLiuTesla/CityGaussian#38]
Hi, as shown in the videos below:

https://github.com/user-attachments/assets/1bc65ea2-82df-4ef0-a958-2afc1878b059

https://github.com/user-attachments/assets/786a71c9-bb02-41f8-bf6e-ecdc57a85d24

**Comment by DekuLiuTesla** [comment]
Hi~ @yzslab , thanks for your valuable feedback. This main reason is mainly due to using the bounding box to approximate irregular block regions for visibility check. When viewing extremely close to the boundary, a sudden block disappearance can happen. One solution is to relax the following `in_frustum` constraint:
https://github.com/DekuLiuTesla/CityGaussian/blob/4a0b0cb7eaa9d593a55d426d94ba15178869b45e/utils/large_utils.py#L137-L138 to:
```
diff = (max_xy - min_xy)
inter = torch.clamp((max_xy - min_xy), min=0)
mask = ((inter[:, 0, 0] * inter[:, 0, 1]) > 0) | ((diff[:, 0, 0] * diff[:, 0, 1]).abs() < 0.5)
```
where 0.5 is a constant that controls the extent of relaxation. But it may slightly slow down the rendering speed.
