### ISSUE TITLE
For building dataset，when saving gaussians, the process has been killed. It does not appear in the Rubble dataset

### ISSUE THREAD

**Issue by lhc991025** [DekuLiuTesla/CityGaussian#39]
![image](https://github.com/user-attachments/assets/1db7b45f-61af-4b23-b7b7-45a5af1905f5)

**Comment by lhc991025** [comment]
I have found the reason for this problem. Is 128GB of memory not enough to store so many Gaussian points? Is there any other solution?

**Comment by DekuLiuTesla** [comment]
Hi~ @lhc991025 128G memory cost seems weird. In our results, the .ply coarse model of the Building scene is 2.1G, and the parallelly tuned one is 3.1G. But in parallel tuning stage the memory cost can be large, since each block saves its own version of the whole scene. This problem is resolved in our incoming V2 version. And you can currently alleviate this problem by using less block dimensions or save only at 30K iteration.
