### ISSUE TITLE
Reduced Point Cloud Resolution Leads to Floaters

### ISSUE THREAD

**Issue by geoeo** [DekuLiuTesla/CityGaussian#50]
Hello,

I have a problem where when I reduce the number of points in my pointcloud I get floater artifacts in the output. When the pointcloud is very dense I dont have them. 

What parameters can I tweak to fix this issue?

**Comment by DekuLiuTesla** [comment]
Hi, @geoeo , it's a bit hard to understand what's happening from the text. Is there any visualization?

**Comment by geoeo** [comment]
So essentially the only thing I changed was the pointlcloud density. I subsampled the pointcloud from ~3Gb to ~300mb with open3d. I did this because the pointcloud is only from 2 camera views and I would need more to reconstruct the whole scene. Now the reconstruction looks like this. 

If possible could you share insight which parameters in the project could be tweaked since there are a lot!  

2 Views ~ 300mb pointcloud

![image](https://github.com/user-attachments/assets/5fb4814e-eb2c-4f36-9004-5fd597b6a22c)

**Comment by DekuLiuTesla** [comment]
@geoeo Indeed it's not a practical way to directly downsample Gaussians since a correct rendering requires specific depth-sorted order of all Gaussians on the ray. If Gaussians with significant contributions are removed, it can generate weird rendering results, as shown in your image. If you need compression, please refer to the pipeline of LightGaussian (supported by our codebase) or other related works.

**Comment by geoeo** [comment]
hmm ok. Thank you for the insight
