### ISSUE TITLE
 Can you provide your GPU VARM ？

### ISSUE THREAD

**Issue by 7yzx** [DekuLiuTesla/CityGaussian#9]
Could you please tell me the configuration of your experimental computer or the VRAM capacity? 
I often encounter out-of-memory issues with my 4090D 24G. Thank you！

I previously use LoD method to prune some merged cells(just 9 cells) of SmallCity, which allowed it to run normally. However, today I trained all 36 cells, but it couldn’t run properly, as the log shows it exceeded the VRAM. 
I have a question: why don’t you prune the Gaussian splatting on every individual cells instead of the merged result?

**Comment by ArSpi** [comment]
I run the MatrixCity/aerial dataset with RTX 3090 24G, but encounter out-of-memory issues when running the mill19/building datasest.

**Comment by 7yzx** [comment]
I previously pruned parts of SmallCity, which allowed it to run normally. However, today I trained all 36 cells, but it couldn’t run properly, as the log shows it exceeded the VRAM. 
I have a question: why don’t you prune the Gaussian splatting on every individual cells instead of the combined result?

**Comment by 7yzx** [comment]
> I run the MatrixCity/aerial dataset with RTX 3090 24G, but encounter out-of-memory issues when running the mill19/building datasest.

maybe the mill19/building datasest resolution is larger.you can set the resolution to 8 to run, but I don't kwon the result is good or not.

**Comment by nurbanu170399** [comment]
Same here. I have RTX4090 but i get "No GPU Available" or "process killed" when i try to train even though there is 24G GPU.

**Comment by nurbanu170399** [comment]
> I run the MatrixCity/aerial dataset with RTX 3090 24G, but encounter out-of-memory issues when running the mill19/building datasest.

May i ask how did you link the directory for LoD exactly ? 
`cd LargeLightGaussian
pip install submodules/compress-diff-gaussian-rasterization
ln -s /path/to/data /path/to/LargeLightGaussian/data
ln -s /path/to/output /path/to/LargeLightGaussian/output
cd ..`
i think im doing something wrong. I get an error : `FileNotFoundError: [Errno 2] No such file or directory: './cikti/mc_aerial_c36_light_50_distill/point_cloud/iteration_30000/point_cloud.ply'`
im assuming it is because of wrong linking. I could be wrong tho.

**Comment by 7yzx** [comment]
> > I run the MatrixCity/aerial dataset with RTX 3090 24G, but encounter out-of-memory issues when running the mill19/building datasest.
> 
> May i ask how did you link the directory for LoD exactly ? `cd LargeLightGaussian` `pip install submodules/compress-diff-gaussian-rasterization` `ln -s /path/to/data /path/to/LargeLightGaussian/data` `ln -s /path/to/output /path/to/LargeLightGaussian/output` `cd ..` I did not quite understand how to link them. i think im doing something wrong. I get an error : `FileNotFoundError: [Errno 2] No such file or directory: './cikti/mc_aerial_c36_light_50_distill/point_cloud/iteration_30000/point_cloud.ply'` im assuming it is because of wrong linking. I could be wrong tho.

`ln -s source_dir target_dir` is soft link.
I have the same error with you in the distill process, you just look the log file in `LargeLightGaussian/logs_prune/mc_aerial_c36_light_50_prunned.log` , you may find wrong. I think the pruned ply file cannot be saved due to insufficient VRAM.

**Comment by 7yzx** [comment]
> > I run the MatrixCity/aerial dataset with RTX 3090 24G, but encounter out-of-memory issues when running the mill19/building datasest.
> 
> May i ask how did you link the directory for LoD exactly ? `cd LargeLightGaussian` `pip install submodules/compress-diff-gaussian-rasterization` `ln -s /path/to/data /path/to/LargeLightGaussian/data` `ln -s /path/to/output /path/to/LargeLightGaussian/output` `cd ..` I did not quite understand how to link them. i think im doing something wrong. I get an error : `FileNotFoundError: [Errno 2] No such file or directory: './cikti/mc_aerial_c36_light_50_distill/point_cloud/iteration_30000/point_cloud.ply'` im assuming it is because of wrong linking. I could be wrong tho.

`ln -s source_dir target_dir` is a softlink, you can use the dir `data` in the `CityGaussian/` easily when you are in the `LargeLightGuassian/` 
you can check the `LargeLightGaussian/logs_prune` dir to see where is wrong, my wrong is in the prune process,the log shows that `CUDA out of memory.`

**Comment by DekuLiuTesla** [comment]
Hi, thanks for your valuable feedback! 

1. In our training, we use A100 40G. 
2. For block_all of MatrixCity aerial view, we noticed that it may cost memory more than 24G when fine-tuning specific blocks. To finish training with limited VRAM, downsampling images or adjusting max_cache_num (we used a rather large 1024) in train_large.py can be a useful practice.
3. Per-block pruning and merging may result in misaligned results and sub-optimal performance. Due to this worry, we prune on merged Gaussians. But it is worth exploring whether worse results do happen. 
4. No GPU Available error can be attributed to limited available memory. `get_available_gpu` will only return GPU id with occupied memory less than 500M. You can rise the mem_threshold to 5000(M) for a looser start condition.

**Comment by 7yzx** [comment]
Thank you for your detailed reply and excellent work!
